columns:
  gender: category
  SeniorCitizen: int
  Partner: category
  Dependents: category
  tenure: int
  PhoneService: category
  MultipleLines: category
  InternetService: category
  OnlineSecurity: category
  OnlineBackup: category
  DeviceProtection: category
  TechSupport: category
  StreamingTV: category
  StreamingMovies: category
  Contract: category
  PaperlessBilling: category
  PaymentMethod: category
  MonthlyCharges: float
  TotalCharges: float
  Churn: category

target_column: Churn
